version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: pyspark_user
      POSTGRES_PASSWORD: pyspark_password
      POSTGRES_DB: pyspark_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./new_init.sql:/docker-entrypoint-initdb.d/init.sql

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql

  pyspark:
    build: .
    container_name: pyspark
    environment:
      SPARK_MASTER: "local[*]"
    depends_on:
      - postgres
      - clickhouse
    volumes:
      - ./app:/app
    command: >
      bash -c "spark-submit /app/main.py"

volumes:
  postgres_data:
  clickhouse_data:
